### ISSUE TITLE
feature request: English regional channels

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#10]
I got tired of the silly red message about regional programs. I see BBC One London is available. I couldn't get other English regional stations to play.
https://github.com/primaeval/plugin.video.iplayerwww/commit/0df9a2cdb083e3b17c4b0611d2de8b3d8e3b70c5#diff-e87f4dd869f897586689ccfd0fa643d5

**Comment by CaptainTK** [comment]
BBC One London will be included in next release.
