### ISSUE TITLE
BBC Three and CBBC new logos

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#101]
BBC Three and CBBC have new logos that need creating sometime.

**Comment by irn-bru** [comment]
A bit late but...

![bbc_three](https://cloud.githubusercontent.com/assets/8867481/16454718/bbc5d8f8-3e09-11e6-8ec2-560026d1300b.png)
![cbbc1](https://cloud.githubusercontent.com/assets/8867481/16454717/bbc5784a-3e09-11e6-8531-42270b1f2661.png)
![cbbc1alt](https://cloud.githubusercontent.com/assets/8867481/16454720/bbc83fe4-3e09-11e6-9329-75a5735443fc.png)
![cbbc2](https://cloud.githubusercontent.com/assets/8867481/16454719/bbc5bf62-3e09-11e6-9aba-1505d20e9dad.png)
![cbbc3](https://cloud.githubusercontent.com/assets/8867481/16454715/bbc5168e-3e09-11e6-8399-dea042d8e8d8.png)
![cbbc4](https://cloud.githubusercontent.com/assets/8867481/16454716/bbc521ba-3e09-11e6-9ba1-51d391a9dabf.png)

Didn't know what version of CBBC you's would want to use so did them all.
