### ISSUE TITLE
Default icons for start categories

### ISSUE THREAD

**Issue by vonH** [vonH/plugin.video.iplayerwww#104]
There doesn't appear to be any default icons for the add-on start. 

Would you like some created?

**Comment by primaeval** [comment]
Create away. :)

I think the addon shortcut button would be better off with iPlayer/Radio categories now because there are so many menu items. A couple of nice icons for them would be good too.

**Comment by CaptainTK** [comment]
By all means, @vonH. If you or somebody else is able to provide some artwork, this would be more than welcome!
