### ISSUE TITLE
ScrapeAvailableStreams fails for some programmes

### ISSUE THREAD

**Issue by CaptainTK** [vonH/plugin.video.iplayerwww#107]
ScrapeAvailableStreams sometimes returns incorrect streams. For example, Signed Language streams are returned even if Signed Language is disabled in settings for "Emergency Rescue Down Under" when accessing the programmes via A-Z

**Comment by primaeval** [comment]
There is only sign and ad for that program. If you look on the episode web page http://www.bbc.co.uk/programmes/b070r6kn there is no link to the main video, just links to BSL and AD in salmon pink under the video duration. They either screwed up or they showed the ad version recently and not the normal version, so its still on iplayer.

The code
```
            url_match = re.search(
                r'<a.*?href="(.*?)".*?list-item-link.*?>',
                li, flags=(re.DOTALL | re.MULTILINE))
```
picks up href="/iplayer/episode/b070r6kn/ad/emergency-rescue-down-under-episode-15" which is ad.

**Comment by CaptainTK** [comment]
You are right, this is a problem on their end, not the add-on.

Weird, I have never seen this before but came across it for a couple of programmes lately.
