### ISSUE TITLE
Radio Favourites/Added are broken

### ISSUE THREAD

**Issue by CaptainTK** [vonH/plugin.video.iplayerwww#113]
Radio Favourites (now Added) still accesses the correct page, but fails to scrape the contents.

**Comment by CaptainTK** [comment]
@primaeval, this is part of your code. Could you please take a look at it?

**Comment by iparr** [comment]
This problem seems to have reoccurred. TV is fine, but no radio shows up in these places ("Following" as well).

**Comment by CaptainTK** [comment]
Thanks for the notification @iparr . #f1cc6d632ba1250ac020696ca9ca0d6362824aee should fix Radio Favourites. I can't seem to get Radio Following to work, not even on the website. The button is simply missing, so it always comes up empty. Removed it for now.

**Comment by iparr** [comment]
Fantastic. Thank you. Can confirm this works.

Incidentally, the 'Following' feature does work on the website for me, but if I add things to 'Favourites' then this provides much the same functionality. A confusing feature and not huge loss!
