### ISSUE TITLE
Live TV Channel logos in Krypton Kodi Estuary Skin?

### ISSUE THREAD

**Issue by Mike-KL** [vonH/plugin.video.iplayerwww#119]
Just a heads up that the BBC Artwork/Icons for Live TV channel are not being positioned/centralized correctly when using latest Krypton builds of Kodi and latest default Estuary Skin.

Switching between Confluence (working fine) and Estuary Skins with Krypton, issue is very obvious with logos appearing in expected location but only top half of logo showing within correct? new? GUI place holder.

PS, Big thanks to all involved in plugin.video.iplayerwww which by the way is working really very well now in Milhouse Krypton nightly builds on my Rpi2
(much more stable for very long periods at highest bitrate settings)

**Comment by Mike-KL** [comment]
Example of issue

![screenshot000](https://cloud.githubusercontent.com/assets/16574667/16812914/8d1bf524-492f-11e6-9f6e-c2de1ce27d83.png)

**Comment by CaptainTK** [comment]
Looks more like a skin issue than an add-on issue. We just tell Kodi which image to load, there is absolutely no formatting done by the add-on. This is all down to the skin.

I think the improved playback is partially due to an updated version of ffmpeg and partially to better servers on the Beeb's end. I also get more stable streams recently and have not updated my Kodi installation.

**Comment by primaeval** [comment]
You are right. All we do is pass an icon. 
https://github.com/vonH/plugin.video.iplayerwww/blob/master/resources/lib/ipwww_video.py#L949
Estuary gets several textures wrong so far. I made a fullscreen wall page and discovered a few problems with it.  
https://github.com/primaeval/skin.estuarywall
There is too much wasted space and missing functionality for my liking.  It looks nice and clean though.

**Comment by ianimacleod** [comment]
Guys. This is great work. @primaeval I checked out your BBC live test add-on, it's great. I would love if there was someway to pull content information - like guide. Especially for the red button stuff. Maybe at least a thumbnail cache for current time...

**Comment by primaeval** [comment]
Finding the Red Button tv guide information is the holy grail for me at the moment. There is some information at tvguide.co.uk but only for 5 channels and they don't match up to the Red Button channels here properly.

I don't think there is enough control over ffmpeg in Kodi to allow doing a thumbnail cache for the channels but there is talk of better support in Krypton for things like multiple video windows. That could help with previewing what's on multiple channels.

**Comment by CaptainTK** [comment]
Won't fix.
