### ISSUE TITLE
Wrong source for some olympic streams.

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#121]
This stream won't play:
http://www.bbc.co.uk/iplayer/episode/b07nm4g2/olympics-day-3-highlights
There is nothing in the normal ParseStreams url
```
NEW_URL = "http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/%s" % stream_id[0]
```
but there is in the pc version:
```
http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/b07nm2p4/atk/********************************************/asn/1/
```
There may be more.

**Comment by CaptainTK** [comment]
Is the server response empty for iptv-all or does ParseStreams fail to detect any streams in the response?

In the first case: Is there any response for other media sets like apple-ipad-hls?

**Comment by primaeval** [comment]
I think that stream might have just been bad luck in the middle of an update.
It gets the right response now but is missing from the Highlights or Search page.
```
http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b07nm2p4
```

**Comment by primaeval** [comment]
The Live: Olympics 2016 collection is actually giving the sport_stream m3u links but we don't handle them correctly.

**Comment by primaeval** [comment]
Any idea how to get the magic number in flash streams?
This is the Live Group
http://www.bbc.co.uk/iplayer/group/p04375l6
This is the flash selector that finds the sport_stream channel.
http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/p04259h7/atk/**********************************/asn/1/
None of the other variations work: 'iptv-all', 'apple-ipad-hls'

**Comment by CaptainTK** [comment]
AFAIK this is part of the flash encryption, so no.

**Comment by primaeval** [comment]
Did you make a note of the other selector methods that we used to use?
I've got all the ones that work for live streams in plugin.bbc.live and none of them work.

**Comment by primaeval** [comment]
I managed to find them with this call:
https://github.com/primaeval/plugin.video.bbc.live/blob/master/main.py#L341
I found it by emulating an iphone in chrome.

**Comment by CaptainTK** [comment]
I believe that's the schedules API which is used by get_iplayer and others. I find it a little fishy and would rather not want to integrate it.

**Comment by CaptainTK** [comment]
I just tried to get one of the VPIDs from the Live Group and I am able to see streams. It is just that ParseStreams is unable to parse them. The format is different.

**Comment by primaeval** [comment]
You might get lucky. All I could find is in plugin.video.bbc.live.olympics.

**Comment by CaptainTK** [comment]
@primaeval, please try the fix and let me know if you find any streams that still won't work.

**Comment by primaeval** [comment]
Nice fix. I'm sure that wasn't possible when I tried last week but I have no evidence to back it up. ;)

**Comment by CaptainTK** [comment]
No worries, I believe you. I am sure they are fiddling around with things all the time during an event like the Olympics. I wouldn't be so sure this fix is bullet proof. ;-)

2.4.0 is submitted to the official repo.
