### ISSUE TITLE
BBC iPlayer License Fee Warning

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#126]
This addon needs a disclaimer or notice about the iPlayer License Fee changes.
I really don't want to get someone fined £1000 because of something we could have easily done.
A good summary of the law is here:
http://www.bbc.co.uk/news/entertainment-arts-37243332

**Comment by CaptainTK** [comment]
I don't see the difference: This has always been the case for live programmes. Now it also affects catch-up content.

**Comment by primaeval** [comment]
The difference is we have never had a disclaimer and we should have because to many people it looks like a BBC endorsed iPlayer addon due to the name and the logo.
There is no information that says you legally should have a license like the official iPlayer apps or website does.
I'm not so bothered about whether we have to but if we can prevent anyone getting fined I think we should do the right thing and warn them first.

**Comment by CaptainTK** [comment]
First of all: I didn't get a notifcation of your reply. I would have answered earlier otherwise.

OK, let's assume we include a disclaimer, what should it look like?

- A nag screen like for the Red Button? Doesn't seem reasonable to me.
- A note in th add-on description? Hardly any user reads that.

**Comment by CaptainTK** [comment]
How do you make that bool persistent? You would need to write it to a dedicated file and load it every time the add-on is launched. I don't think you can include this in the settings file if the dialog appears somewhere other than the settings.

**Comment by primaeval** [comment]
You don't need add a setting in the settings.xml. 
Just use a
```
xbmcaddon.Addon('plugin.video.iplayerwww').setSetting('licence.warning.seen','true')
```
 command to make one in the code and check it on the index page. 
```
license = xbmcaddon.Addon('plugin.video.iplayerwww').getSetting('licence.warning.seen')
if license and license == 'true':
 carryOn

```
You probably have to check for None first. I can't remember.
Do you want me to have a go at it today?

**Comment by CaptainTK** [comment]
Ah, that sounds interesting, I wasn't aware of that option.

If you got time today, please go ahead. I may be able to get a release out tonight or tomorrow morning. After that I'm off again for two weeks.

**Comment by primaeval** [comment]
Here you go.
https://github.com/vonH/plugin.video.iplayerwww/pull/127
