### ISSUE TITLE
Tried it on Kodi Direct 3.1., get error and the following log

### ISSUE THREAD

**Issue by xyladecor** [vonH/plugin.video.iplayerwww#131]
File "/usr/lib/enigma2/python/Plugins/Extensions/KodiDirect/plugins/plugin.video.iplayerwww-master/default.py", line 21
    from __future__ import division
SyntaxError: from __future__ imports must occur at the beginning of the file

**Comment by CaptainTK** [comment]
Thanks for opening this issue.

1. I can't find KodiDirect on the Kodi website. Where can I find it and what does it do?
1. The error sounds like you just need to change the order of imports such that future is imported first. Have you tried if this resolves the issue, @xyladecor?

**Comment by CaptainTK** [comment]
Closing because we cannot duplicate the issue. Please reopen if the problem persists.
