### ISSUE TITLE
feature request: filter menu options

### ISSUE THREAD

**Issue by Thomas-O** [vonH/plugin.video.iplayerwww#132]
Hi,

Please consider adding a menu edit option to the add-on's preferences. With which the user hide can one or more of 19 menu options.

My Kodi is used exclusively for audio / music. I would like to simplify the menu by displaying just the Radio options.

Thanks for your time.

_Thomas_

**Comment by CaptainTK** [comment]
That is already possible if you start the add-on by clicking on the Audio->Add-ons button. It will only show video and radio content at the same time if you use a shortcut. In this case, it is impossible for the add-on to know if it is supposed to show audio or video content.

Does this solve your issue, @Thomas-O?

**Comment by Thomas-O** [comment]
I tried your suggestion with the confluence skin and it works brilliantly. However, I'm accessing the add-on via a custom shortcut on the mimic homescreen. A skin where the default (and the family's preference) is for confusing sub-menus to be disabled. Hence the problem and the request. 

Sorry if it's a lot of bother, it's just that I like my Kodi box's set-up to be simple. Like its owner.

**Comment by primaeval** [comment]
The problem is that iplayerwww is a dual-media provider but the skin shortcuts aren't that specific.

If you have the option in your skin you probably could use the shortcut that Favourites makes.
`ActivateWindow(10502,&quot;plugin://plugin.video.iplayerwww/?content_type=audio&quot;,return)`
for Music or
`>ActivateWindow(10025,&quot;plugin://plugin.video.iplayerwww/?content_type=video&quot;,return)`
for Video.

Another option is to use a Favourites handler like Super Favourites or my Simple Favourites or Video Favourites. Then you can really strip the addons down to just the bits you need.

**Comment by chewitt** [comment]
Krypton promotes Favourites from a buried pop-up to the Home Screen menu which makes access to persistent items inside the iPlayer add-on that have been bookmarked easier. Not a replacement for deeper settings configuration, but worth investigating.

**Comment by Thomas-O** [comment]
I'll have a go with the favourite shortcut. Thanks very much for the suggestion.

Unfortunately I'll have to wait for the Krypton Favourites - my WeTek Core is still running Jarvis.  

One thing that has occurred to me is the filter option. If I enter Radio in to the advanced filter box then I'll see only the 7 Radio options I need and want. However, when I return to the add-on the filter has vanished. Is there any way to make the filter permanent? Just for this section: the rest of my library's going to look a little spartan if it's applied everywhere.

**Comment by primaeval** [comment]
If you mean the Filter on the left side in Confluence it is only applied until you play a link.

If you want to have a go with my Simple Favourites you can start here:
http://forum.kodi.tv/showthread.php?tid=293511

or Super Favourites (which is in the main Kodi repo)
http://forum.kodi.tv/showthread.php?tid=192662

Both will do a similar job of making custom Folders for your Favourites so you could just select the Radio stations and programs you like.

Another option is to make a keyboard shortcut to go straight to the Radio section if you use it all the time but that is getting a bit advanced.

@CaptainTK I think it was you that actually suggested having an extra top level menu for iPlayer and Radio at one stage. Maybe that would be a good idea if the addon isn't run from Video or Music, to reduce the item count. It's another click compared with a scroll.

**Comment by primaeval** [comment]
@Thomas-O I just made you a custom addon called Audio Favourites in my repo. You can add the Radio links in there and make a shortcut on the Home page if you like.

![audio_favourites](https://cloud.githubusercontent.com/assets/11716348/20466381/a57c0916-af72-11e6-89cc-2425d55f67b8.PNG)

**Comment by Thomas-O** [comment]
Blimey, that's fantastic. Thanks for being so kind and considerate. I'll give it a go some time tomorrow and report back.

The top level menu also sounds like a top idea. Everything in its right place.

**Comment by Thomas-O** [comment]
Problem solved thanks to the mighty primaeval. Without the surplus options the screen is much simpler and cleaner. It's just what I wanted.

Though in the long-term it might be worth considering the extra menu layer. Perhaps as an option in the add-ons settings. 

Thanks so much for your help and advice.

Thomas

**Comment by primaeval** [comment]
Thanks. I see you read the acknowledgements. ;)
