### ISSUE TITLE
RPi-OpenElec7.0 Errors with catchup

### ISSUE THREAD

**Issue by keysersoze1977** [vonH/plugin.video.iplayerwww#137]
Hi All,
Am running OpenElec 7.0.1 on RPi3 with iplayer WWW 2.5.3 installed.  I using VPN Manager for OpenVPN.

The live streams work fine but the catch up programs do not.  I get an errors.  Can anyone help or suggest anything?  Here is the log.  Thanks.

http://paste.ubuntu.com/23905221/

**Comment by CaptainTK** [comment]
Looks like the Beeb thinks you're not in the UK.

Please disable your VPN and confirm you are in the UK. If the problem still persists, please reopen this ticket. Otherwise, please discuss with the Beeb why they block your VPN.
