### ISSUE TITLE
Search Not Working (or Very Slow)

### ISSUE THREAD

**Issue by ihurst** [vonH/plugin.video.iplayerwww#14]
Using latest version 1.2.2 I am searching for "Doctor Who" and getting no response. The system "working..." message is just displayed.

I'm going to look into this, but thought I'd raise a bug to check if anyone else can reproduce.

**Comment by CaptainTK** [comment]
It is very slow (as usual), but it works perfectly fine here.

**Comment by ihurst** [comment]
How long does it take for you to get results?

**Comment by CaptainTK** [comment]
I guess 30-60 seconds.

**Comment by ihurst** [comment]
There definitely appears to be an issue here for me. If I do a simple search i.e. "Twirlywoos" (1 result) every thing is working fine.

But when I search for "Doctor Who" (large result set - lots of pages) I get the following errors when I get to processing about page 6:

21:32:26 T:1969532928   DEBUG: SECTION:UnloadDelayed(DLL: special://xbmcbin/system/ImageLib-arm.so)
21:32:26 T:1969532928   DEBUG: Unloading: /ImageLib-arm.so

Need to have a look at see if I can find what is causing this error. The reason I am looking at this is because I'm  looking at #3 - which I have nearly completed :)

**Comment by CaptainTK** [comment]
Are you logged in with your BBCiD when you perform the search?

If so, please try to log off and then repeat the search. Perhaps search behaves differently whether you are logged in or not.

**Comment by ihurst** [comment]
Not logged in when I'm performing search.

This seems to be a lower-level issue than our iplayer code directly. I'll have to investigate. But no one else appears to be reporting :(
