### ISSUE TITLE
BBC South West missing

### ISSUE THREAD

**Issue by btrewern** [vonH/plugin.video.iplayerwww#140]
Looks like BBC South West is missing.

I think I could make a guess at what needs changing to get this working but don't have a clue how to get a development version of Kodi up and running.  Is there somewhere with pointers on how to get started?

**Comment by CaptainTK** [comment]
No need for a Kodi development version. You can modify the add-on with a simple text editor.

However, if you can simply post a link to the live stream of BBC South West on the iPlayer website, I am positive I can add it soon.

**Comment by primaeval** [comment]
I think you just need to add bbc_one_south_west in 2 places:
https://github.com/vonH/plugin.video.iplayerwww/blob/master/resources/lib/ipwww_video.py#L123
https://github.com/vonH/plugin.video.iplayerwww/blob/master/resources/lib/ipwww_video.py#L1242
It works for me.

**Comment by btrewern** [comment]
OK.  Currently I am on a Mac and can't find where the Kodi add-ins are installed.  Any pointers would be great.

I've had a look to find links to a BBC South West stream but can't anything specific.

There is a link to change your settings to use BBC South West which is: 
`http://www.bbc.co.uk/iplayer/live/bbcone#south_west`

**Comment by CaptainTK** [comment]
Thanks a lot for the hint, @primaeval.

I will add this with the next release, @btrewern.

**Comment by btrewern** [comment]
@CaptainTK Thanks, that would be great.
