### ISSUE TITLE
Automatically enabling inputstream.adaptive

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#160]
Hi. Have you had a look at enabling inputstream.adaptive in code with the json rpc Addons.SetAddonEnabled function. Lot's of users seem to be getting stuck enabling it.

Here is a good discussion with lots of code examples.
http://noobsandnerds.com/support/archive/index.php?thread-17427-1.html

**Comment by CaptainTK** [comment]
Sounds interesting, thanks for the link.

I will take a look at it once I am back from my holidays.

**Comment by primaeval** [comment]
You are always jet-setting. ;)

**Comment by mbcoder** [comment]
+1 for this improvement, I too fell into the same trap and being new to OSMC would have appreciated this to just work.

Great app once I got it working though...

**Comment by CaptainTK** [comment]
This is no longer required. Matrix should ship with inputstream.adaptive automatically.
