### ISSUE TITLE
BBCid login changed

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#166]
They seem to have changed the login protocol quite a bit. They are using account.bbc.com now.

@ihurst It might be time to dust off your debugging setup if you have the time.

**Comment by primaeval** [comment]
I think they are using the new https protocols too so it probably won't be fixable on Kodi Jarvis. SPMC should be ok.

Have you two got time to look at this or do you need some help?

**Comment by CaptainTK** [comment]
I should be able to put in some work tonight, but help is always appreciated, especially with these nasty login issues.

**Comment by CaptainTK** [comment]
Hmm... Feels like that was too easy. Hope this was really it.

**Comment by primaeval** [comment]
Well spotted. I thought it had completely changed because the ip addresses where so different.
