### ISSUE TITLE
Episode pages have changed

### ISSUE THREAD

**Issue by CaptainTK** [vonH/plugin.video.iplayerwww#171]
The design of the episode pages for iPlayer have changed. As a consequence, the scraping of episode IDs fails.

**Comment by primaeval** [comment]
I'm Watching this for clues.
https://github.com/get-iplayer/get_iplayer

**Comment by CaptainTK** [comment]
No need. I almost got it figured out. They also changes something in the mediaselector format at the same time. This is where I am currently struggling.

**Comment by primaeval** [comment]
These are the mediaselector lines from the log if that helps;
```
http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/b047wtln/transferformat/hls?cb=27546
http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b047wtln/transferformat/dash?cb=66602
http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b047wtln/transferformat/hls?cb=66171
http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/b047wtln/transferformat/dash?cb=59239
```

**Comment by CaptainTK** [comment]
It wasn't the mediaselector itself. It was something I broke in the code. Sorry for misleading you. Looks like I need some dinner. But let's commit something first! :-)

**Comment by primaeval** [comment]
The json should be more reliable, until it dies next year. ;)

**Comment by CaptainTK** [comment]
I don't want to access something that is not part of the website. Plus: What we get here is essentially also json. It is simply embedded in HTML and needs to be extracted.

**Comment by primaeval** [comment]
I didn't look carefully enough. It looked like you pullled in the whole json url but it is just the match. 

I can only get the Akamai streams on Jarvis due to https. I hope they don't meddle with that. I really don't want to have to put up with Krypton's delay problems.

Well fixed anyway... until tomorrow. ;)

**Comment by primaeval** [comment]
get_iplayer are screwed though for the moment as they have been relying on the xml feeds.

**Comment by CaptainTK** [comment]
I don't have any delay problems on Krypton. But then again, I am running Linux.

**Comment by primaeval** [comment]
Not even when you start an HLS stream? It is really noticable from a TV Guide when you are trying to channel surf even though it is only a second or two from iplayerwww or a direct line to an hls substream.

**Comment by CaptainTK** [comment]
No, the delay is the same for HLS and DASH on my machine.

**Comment by primaeval** [comment]
Have you done an A/B comparison with Jarvis? It is instantaneous in Jarvis for me.

**Comment by CaptainTK** [comment]
No, I don't keep multiple installations around. Krypton might be slower than older versions, but I am pretty sure there is no difference between HLS and other streams.

**Comment by primaeval** [comment]
It's not much but when you notice it it is too annoying especially when you know it could easily be fixed.
