### ISSUE TITLE
Jarvis https

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#176]
Hi. There are a couple of tricks to ignore https errors that seem to work in Jarvis that I use in my BBC TV addon. I'm only using akamai so it might not help with bidi but it gets around some problems.

disable_warnings(InsecureRequestWarning)
https://github.com/primaeval/plugin.video.bbc/blob/master/main.py#L13

requests.get(url,headers=headers,verify=False)
https://github.com/primaeval/plugin.video.bbc/blob/master/main.py#L55

I've also added in a pvr scheduler as get_iplayer is out of action for a while.

**Comment by CaptainTK** [comment]
Thanks for the hints. I was more thinking to add an option to 2.5.x to ignore HTTPS streams altogether. Should only be a couple of lines of code. As long as there are still HTTP streams, this would solve the whole issue.

**Comment by primaeval** [comment]
I'm starting to see more and more https streams for iptv channels the last few weeks. Someone's paranoia level must have gone up. ;)

**Comment by primaeval** [comment]
More people are switching to SPMC when they come across the https issue. I can do some tests on that if you haven't got access to it.

**Comment by CaptainTK** [comment]
AFAIR these hints no longer work, so I am closing here. In case my memory is wrong, please reopen.
