### ISSUE TITLE
feature request: show/hide channels

### ISSUE THREAD

**Issue by chewitt** [vonH/plugin.video.iplayerwww#2]
It would be nice to have an option to exclude specific channels from listings and searches, i.e. BBC Alba and S4C for those of us that don't speak Scottish Gaelic or Welsh, or the ramblings of politicians on the BBC Parliament channel.

**Comment by CaptainTK** [comment]
In which part of the add-on exactly would you want to apply these filters?
* Live TV?
* Highlights/Most Popular?
* Categories?
* A-Z?
* Search?

Just trying to understand what you need to see if it is possible at all.

**Comment by chewitt** [comment]
"all of the above" would be nice, but it's most evident with A-Z and categories as you often get a large block of related (but undesirable) content to scroll past.

**Comment by CaptainTK** [comment]
It is definitely not possible for A-Z. The information is simply not there at all.

Anything else will only work partially as well. The information which channel a programme belongs to isn't always available.

So I am afraid that even if this was added, it probably wouldn't give you what you are looking for.

**Comment by CaptainTK** [comment]
Won't fix.
