### ISSUE TITLE
Add-on failes for UTF-8 encoded programme names

### ISSUE THREAD

**Issue by CaptainTK** [vonH/plugin.video.iplayerwww#20]
The add-on will fail with an error like this:

> Error Type: <type 'exceptions.UnicodeDecodeError'>
> Error Contents: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

if the name of a programme contains UTF-8 encoded characters. This frequently happens for Scottish content, for example Channel Highlights->Alba or Categories->Scotland.

**Comment by ihurst** [comment]
See pull request #21 this has fixed the two issues. 

But currently Highlights is not working in this branch? No results.

**Comment by CaptainTK** [comment]
Unfortunately https://github.com/vonH/plugin.video.iplayerwww/pull/21 didn't solve all of the issues. There are still errors whenever names are built up from different strings and some of them may be UTF-8 encoded.

I am taking a look at it now.

**Comment by ihurst** [comment]
Sorry hope my code helps.  I can't do much tonight. 

-------- Original message --------

**Comment by CaptainTK** [comment]
The problem is, that the whole HTML code is UTF-8 and sometimes it actually contains UTF-8 characters. So the easiest fix is to decode the whole HTML to ASCII in OpenURL.

@ihurst please consider if this may also be necessary for OpenURLPost. Thanks.

**Comment by ihurst** [comment]
This is not necessary on OpenURLPost as I return the whole response object as I need to look at the http status code.

See my comment on the change you made, as there may be a cleaner option.
