### ISSUE TITLE
db17c5e6640a0c799cf31c8b0d3598a798f475aa breaks compatibility with PseudoTV Live

### ISSUE THREAD

**Issue by CaptainTK** [vonH/plugin.video.iplayerwww#23]
The change from xbmcplugin.setContent(int(sys.argv[1]), 'movies') to xbmcplugin.setContent(int(sys.argv[1]), 'episodes') in db17c5e6640a0c799cf31c8b0d3598a798f475aa breaks compatibility with PseudoTV Live export.

The change to episodes was made to allow the usage of the 'aired'-InfoLabel.

@cas-- can you please check if the 'aired'-date can be supplemented by another InfoLabel for content-type 'movies'?

**Comment by Lunatixz** [comment]
If this is the only issue you guys have, setting content, I'll just add support for episode types. I was using "Movies"/"TVShow" not many plugins use episodes.

**Comment by CaptainTK** [comment]
Yes, that seems to be the only issue. It would be great if you could add support for episodes.

Neither movies nor TVShow offers support for the aired-date.
