### ISSUE TITLE
remove html tags in file name

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#24]
See current highlights page for Doctor Who "Series 9 - Omnibus: 1. The Magician's Apprentice/The Witch's Familiar". Its full of \<span\>'s.

**Comment by CaptainTK** [comment]
This should be easy to fix, but I am off for the weekend, so it takes some time till I can get to it.

**Comment by primaeval** [comment]
I've got a fix but I'll have to rearrange my branches for a clean pull request.
https://github.com/primaeval/plugin.video.iplayerwww/commit/bddb7b2937bea1ae5321e9354fa7b8faca6fefbc

**Comment by CaptainTK** [comment]
Sorry, saw your fix too late. I think you tried to fix it in too many places anyways. This strange tags are currently only used on the Highlights pages.

**Comment by primaeval** [comment]
Just future proofing. Did you see my next 2 commits? There are other tag bugs.
