### ISSUE TITLE
GetEpisodes list incorrect for Radio series

### ISSUE THREAD

**Issue by zeripath** [vonH/plugin.video.iplayerwww#254]
Hi!

Thanks for all your work.

It looks like BBC have changed the format of their Radio programme lists - meaning that episodes in a series are being listed as ' - ' and can no longer be listened to. For example, take a look at 'Programme List A-Z' > 'R' > 'BBC Radio 3 - Record Review'

**Comment by zeripath** [comment]
It looks like the masthead_title and the name have changed slightly:

```
alternative_masthead_title_match = re.search(r'<div class="br-masthead__title">.*?<a href="[^"]+">([^<]+?)</a>', html, re.M | re.S)
```

```
alternative_name_match = re.search(r'<meta property="name" content="([^"]+?)"', programme)
```

Now this just makes the lists correct but unfortunately I cannot get the streams to play and it seems that the vpid field is no longer present on the programme's url e.g.: http://www.bbc.co.uk/programmes/b0b9vw0x

**Comment by zeripath** [comment]
OK, so it looks like instead of looking at http://www.bbc.co.uk/programmes/b0b9vw0x you should be looking at http://www.bbc.co.uk/programmes/b0b9vw0x/playlist.json

**Comment by CaptainTK** [comment]
Thanks a lot for the proposed fix in #255 . Looks good to me.

I am not sure what you refer to in your last comment, though. What is the relation to the json?

FYI: I know there are several options to parse JSON directly. However, I refrain from doing so, as they may change that at any time. Only JSON which is embedded in a website seems acceptable to me.

**Comment by zeripath** [comment]
Sorry I was unclear.

Unfortunately the vpid has been moved out of the original programme url and now can only be found in playlist.json, hence the changes to AddAvailableStreamItem(...)

**Comment by CaptainTK** [comment]
Thanks, now I get you. I think there is a more elegant way to fix this. http://www.bbc.co.uk/programmes/b0b9vw0x will direct you to https://www.bbc.co.uk/radio/play/b0b9vw0x when clicking on play. I think we should try to use that right away. It will automatically include the JSON.

**Comment by zeripath** [comment]
Ah that's cunning. I just looked at what get_iplayer was doing and copied that.
