### ISSUE TITLE
highlights has gone 100% cpu crazy

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#26]
ListHighlights is getting stuck on the first match1 and locking up Kodi.

**Comment by primaeval** [comment]
Here is a file dump of the problem highlights.
https://github.com/primaeval/plugin.video.iplayerwww/blob/master/errors/highlights.html

**Comment by primaeval** [comment]
`<em>`has changed to `<strong>`
https://github.com/primaeval/plugin.video.iplayerwww/commit/0fe887683ffef27e650c15cfe5dbe25bacdba2ed

**Comment by CaptainTK** [comment]
Thanks. That did it!

**Comment by primaeval** [comment]
I still don't understand why findall went mental and didn't just give up.
