### ISSUE TITLE
iplayerwww unable to play BBC Proms - Prom 26: Late Night Serpent and Fire

### ISSUE THREAD

**Issue by zeripath** [vonH/plugin.video.iplayerwww#262]
Hi!

Thanks for all your work... I've just tried to play "BBC Proms - Prom 26: Late Night Serpent and Fire" (pid: b0bclyqr) and unfortunately this doesn't work, it seems that there is a bug in the ScrapeAvailableStreams function. 

The issue lies in resources/lib/ipwww_radio.py:744:

```
match = re.search(r'window.__PRELOADED_STATE__ = (.*?);', html, re.DOTALL)
```

which doesn't work if the json contains a ';'.

Looking at the structure of the html page it appears that the definition of `window.__PRELOADED_STATE__` is wrapped in its own `<script>` tags, so a relatively simple fix would be to change the line to:

```
match = re.search(r'window.__PRELOADED_STATE__ = (.*?);\s*</script>', html, re.DOTALL)
```

**Comment by CaptainTK** [comment]
Good find, thanks. This may as well occur in the video json. Let's hope they keep it clear of semicolons.

Unfortunately, I wasn't able to take a look earlier and Prom 26 is no longer available. I trust that you checked this and since I see no side effects, I will release fixes.
