### ISSUE TITLE
Folders missing

### ISSUE THREAD

**Issue by unalterable** [vonH/plugin.video.iplayerwww#272]
Iplayer seems to have adjusted the way they display series. You now have to search for the latest episode and then click through to past episodes.

Could you incorporate this - because now i only seem to be able to use your plugin to see the latest episode of anything.

**Comment by CaptainTK** [comment]
I know this happened for Highlights, and I will not fix it there. Last time I checked it still worked for A-Z and Categories.

Can you please clarify which path you used?

**Comment by unalterable** [comment]
I understand that you would not fix it for highlights - having only single episodes there makes sense.

I am talking about categories and A-Z search. The change occurred in the last few days - and i have recognised a change in the iplayer website UI too. 

The following paths used to have folders on them - but now only the latest single episodes can be seen.
iPlayer WWW >> Categories >> News (i used to find a "Click" folder and a "Newsnight" folder but now only the latest episodes)
iPlayer WWW >> Categories >> Entertainment, Food, Documentaries, Comedy (all the same - used to have folders for shows like "Mock the week" and "QI", now only latest episodes.
iPlayer WWW >> Search >> *type "killing eve" (used to get results with a folder for the new drama "killing eve" - now only the last episode is shown in the results).

Interestingly - i did record the path to the show folder for "Killing Eve" in kodi favourites, and that works - but i can no longer get to that view via the plugin. But the bbc endpoint for getting the episodes for a series must still be working - but i surmise the schema for category and search results has changed.

I notice that the update to the iplayer website now pushes you to follow a altered path through their UI. Categories/Search >> Recent episode >> View all episodes
rather than the old path 
Categories >> Popular show >> episode

I surmise the search and categories have recently been updated for a UX revamp on the iplayer website. One which focuses much more heavily on discovery through recent episodes, rather than through the shows.

I don't know how you might solve it but it makes this plugin extremely limited otherwise. Please let me know if i can help.

**Comment by CaptainTK** [comment]
Thanks for the update. I will look into it.

The main challenge is that we now can't recognise any longer if a programme is a single episode of a collection. If we dive into each programme to find out, this will look like a DoS attack to the Beeb. Unfortunately Kodi requires the list item type (folder or playable) to be set on advance.

**Comment by CaptainTK** [comment]
AFAIK there are no modal dialogs in the Kodi add-on interface. So no, I can't do that.

The only way out I can see right now is to change all items to folders. This way, you cannot play any programmes from the top folder anymore, but would need to get an episode listing first, even if there is only one episode.

**Comment by primaeval** [comment]
You can still go through the programmes index instead of the iplayer index. eg
https://www.bbc.co.uk/programmes/a-z/by/e/player

It will need a bit of sifting as the radio and tv programmes are intermingled.
