### ISSUE TITLE
Highlights: typo--canary

### ISSUE THREAD

**Issue by ihurst** [vonH/plugin.video.iplayerwww#28]
The highlights menu items are displaying incorrectly again for example:

Cuffs: typo--canary">Episode 1<

**Comment by ihurst** [comment]
Should we remove highlights capability? It really is just a UI for the iplayer website. Users of our plugin will probably want to go direct to channel listing etc.. Think we need to think about actual use-cases for the kodi implementation of iplayer.

**Comment by primaeval** [comment]
Highlights is the reason I use this over Mikey's.

**Comment by ihurst** [comment]
@primaeval I didn't know about Mikey's plugin. This may sound like a stupid question but what do you expect to see in highlights section? I'm just trying to get a better idea of the use-case to work out what we should be displaying. (i.e. should we include Most Popular? When we already have that as a separate category)

**Comment by ihurst** [comment]
This was caused by my last change that has been merged into the trunk. @vonH  I'm going to put the fix against this issue, but please note that your current master is broken. Sorry.

**Comment by CaptainTK** [comment]
I plan to take a different approach on Highlights in the future. However, I am unable to contribute, fix or release anything in the next three weeks due to work.

**Comment by CaptainTK** [comment]
I believe this was fixed with the last pull request. If that's not the case, please reopen.
