### ISSUE TITLE
BBC iPlayer with a VPN

### ISSUE THREAD

**Issue by EGGMANCAN** [vonH/plugin.video.iplayerwww#296]
I am using OpenVPN on my device with Kodi installed and the BBC iPlayer WWW add-on. BBC iPlayer does not allow catch-up programs to be viewed using a UK VPN. Is there a way for me to bypass my VPN connection only for the BBC iPlayer WWW Kodi add-on? I would still like the VPN to be active across all of my other Kodi add-ons, if only there was a way to disable/bypass it with BBC iPlayer WWW.

**Comment by CaptainTK** [comment]
As far as I know, this is not possible. If you enable a VPN, you do so on an operating sytem level (Windows/Linux/Android). After activating the VPN all traffic on your system will run through the VPN. Kodi does not even "know" you are using a VPN, it simply uses the network stack of the operating system.

On a side note: This is not an add-on issue, but a question. Please ask in the forum.

**Comment by EGGMANCAN** [comment]
Would it be feasible to add a proxy settings menu to the iPlayer WWW plugin?

**Comment by CaptainTK** [comment]
No, this is not feasabile for two reasons:

1. Proxys in add-ons are not allowed on the official Kodi add-on repository. The reason for this is that proxies are mostly used to bypass geoblocking, which cannot be supported for legal reasons.
1. Even if a proxy would be defined in the add-on, my understanding is that this would only work on the scraping part of the add-on. Kodi's video player will revert to the default proxy settings of Kodi.
