### ISSUE TITLE
Picky pedant alert

### ISSUE THREAD

**Issue by Thomas-O** [vonH/plugin.video.iplayerwww#339]
I know this is a ridiculous question: I'd like to edit the add-on to remove the iPlayer: prefixes in the menu category list - just to make it look a little nicer and less cluttered. Please could you tell me where to make the edits?

Thanks for your help.

Thomas

**Comment by CaptainTK** [comment]
Edit the value of

`
msgctxt "#30323"
msgid "iPlayer: "
msgstr ""
`


in strings.po. Hope that helps.
