### ISSUE TITLE
Installation fails on fresh install of latest OSMC with unsatisfied dependency for script.module.idna v 2.6

### ISSUE THREAD

**Issue by freddieFishCake** [vonH/plugin.video.iplayerwww#340]
Absolute newbie to OSMC. Installed the latest (2020.11 I think) to Raspberry Pi 3.
Tried to install iplayer WWW from repository and got the error message about unsatisfied dependency.
Downloaded the master zip file from this GitHub and did an Install from zip file -> same error message.
Googling for script.module.idna finds this hit for version 2.8
https://mirrors.kodi.tv/addons/krypton/script.module.idna/
but I don't know anything about Python or OSMC so am not sure how to proceed from there.

**Comment by CaptainTK** [comment]
That add-on is not required by iPlayer WWW. I can only assume that it is required by one of the dependencies of it, most likely Python Requests. I never encountered this issue before, so I really cannot give you any advice here.

**Comment by freddieFishCake** [comment]
Thanks.
OSMC lists the dependencies for iPlayerWWW as:
requests:
scripts.module.requests 2.7.0
urllib3:
scripts.module.urllib3 1.22
chardet
scripts.module.chardet 3.0.4
script.module.idna
not available
certifi
scripts.module.certifi 2017.07.27.1

So idna looks like it is a transitive dependency from urllib3 / chardet.

**Comment by freddieFishCake** [comment]
.. and the version of urllib3 in the kodi repo seems to be a later version:
https://mirrors.kodi.tv/addons/krypton/script.module.urllib3/
shows 1.25.6
perhaps that later version has a dependency to the later idna (2.8) that is in the kodi repo?

**Comment by tdobson** [comment]
I also have this error

**Comment by CaptainTK** [comment]
Which version of Kodi are you using, and which platform are you running on, @tdobson ?

As @freddieFishCake correctly explained, this is a transitive dependency of urllib3. Not much I can do about it.
