### ISSUE TITLE
Cannot play BBC 2 live

### ISSUE THREAD

**Issue by unalterable** [vonH/plugin.video.iplayerwww#341]
In the last few days, attempts to play BBC2 live fail. A modal appears saying "available in UK only". I AM in the UK.
I am using  v 3.0.49. And I don't get the error with other channels or recorded TV.
I also tried entering my BBC credentials into the add-on but to no avail.

**Comment by CaptainTK** [comment]
This requires a bigger rewrite to work again. The HLS part was done in https://github.com/vonH/plugin.video.iplayerwww/commit/e421f374d9b1d23b59aa2df2fb5031df37d7ecb0, DASH needs some more work after merging the HLS part into Krypton here: https://github.com/vonH/plugin.video.iplayerwww/commit/9a8c6641dcfdd17fef47b326590eb098516ac8a0.

**Comment by CaptainTK** [comment]
DASH has been implemented as well, but playback still fails. Most likely due to a bug in inputstream.adaptive:

https://github.com/xbmc/inputstream.adaptive/issues/560

Closing here since this cannot be fixed in this add-on, but needs some love from @peak3d.

**Comment by matthuisman** [comment]
can someone please test with:
https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-564/7/artifacts

Please advise if that works

**Comment by unalterable** [comment]
I don't know how, but the channels seem to be back...
I performed no updates... So hopefully it has been fixed at the BBC end.
