### ISSUE TITLE
Watched status not syncing

### ISSUE THREAD

**Issue by kevwag** [vonH/plugin.video.iplayerwww#349]
The addon updates and maintains the locally stored watched status of shows but it does not sync the status back to the BBC site. 
This is incredibly frustrating because it stops the "Watching" (next episode) list from working properly. 
To be able to use the watching list (arguably one of iPlayer's best features), you have to open iPlayer in a web browser (or official BBC android app) and manually trick the site into thinking you've watched the episode by playing the first 30 seconds and then skipping forward to the end credits. Once you've done that you can go back to Kodi and the next episode will appear in the Watching list but this is nothing short of infuriating when you have several different shows in-progress.

Please could you fix the add-on so that it : 
a) Marks shows as "in-progress" on the BBC site when you start to watch something new using the Kodi add-on.
b) Marks shows as "watched" on thee BBC site when watched on the Kodi add-on so that the "Watching" list updates as it should.

**Comment by CaptainTK** [comment]
Interesting idea.

To be honest, I don‘t know if this is possible at all, but I will look into it in the future.

If you need to really play back the episode on the website to reach the watched state it is very unlikely that this can be emulated by the add-on. Simple reason: Everything that is related to playback is handled by Kodi or inputstream adaptive. Both are pretty generic and will not support custom functions like those used by the BBC player on the website.

If I can determine some specific call which will set the watched status, it should be possible to implement the same in the add-on.

**Comment by kevwag** [comment]
You don't have to watch the full episode on the website, it seems like their player triggers events at certain points during playback. A show (or episode) gets marked as "in progress" somewhere around the 30 second point but you don't have to actually watch the whole first 30 seconds, you can start playback and then immediately skip to 00:00:29 and let it play for two seconds - that is enough to set the status marker to "in-progress". After that you can skip ahead to the end credits and let them play out, which will then mark the video as "watched".  It's worth noting at this point that you cannot simply skip to the second step without doing the first part, the video has to have "in-progress" status set first before it can progress to "watched" status.

I'm a techie but not a programmer so I can't directly suggest any code as such, but if you're reverse-engineering from the BBC site, I would say I'm 90% sure that one, maybe both of the calls you're looking for are hidden within the countdown popup which appears near the end of a show if autoplay is enabled - it marks the episode as watched and then moves to the next one.

**Comment by CaptainTK** [comment]
The website player appears to post messages to

`https://ibl.api.bbc.co.uk/ibl/v1/user/plays`

whenever the status changes, and in intermittent intervals in between. There are start, pause, and heartbeat messages. Each message consists of four fields:

1. action - this is either "started", "paused", or "heartbeat"
2. id - this is the programme PID, e.g. "m0015yj1"
3. offset - this is an offset in seconds from the start of the programme, e.g. 125
4. version_id - this is the stream id, e.g. "m0015yj0"

This way the beeb can check which programme you are watching, and even if you try different versions of it, e.g. standard and audio described. I believe this would need to be implemented to duplicate the same functionality.

Sending such a message to the server on starting a stream in Kodi should be relatively easy. However, updating it during playback is - to my knowledge - not possible. The add-on simply passes the stream URL to the Kodi player, which does the rest. There is no message like "playback complete" upon returning to the add-on.

So as far as I can see, the only thing I _can_ do right now is to get shows appear on the watching list. I _cannot_ set them to "watched" automatically.

**Comment by kevwag** [comment]
@CaptainTK 
 I understand what you're saying but I'm sure there must be a way around this since so many other addons manage to track progress somehow. (Example: discovery+ by @Dis90 tracks watched episodes and even offers to resume if you stop playback part-way through)

**Edit:** I believe that at least some of these addons use the callback methods "onAVStarted()" and "onPlayBackEnded()" to get the "playback started / complete" messages you're talking about.

Even if you can't find a way to solve this "automatically", a working option to "Mark as watched" manually in the context menu would be a huge improvement as it would allow the watchlist to move on without having to open iplayer on another device to simulate watching what you just watched in kodi. (Incidentally, I just visited the website to do just that and I noticed that BBC have changed their web player some time in the last 7 days. I'm not sure if that's relevant or useful but thought it might be worth mentioning.)

**Comment by kevwag** [comment]
@CaptainTK 
Further to what I previously said, I've observed things a bit more closely and I think maybe you're looking at this problem from the wrong angle:
You say the issue is that you can't get progress information from the player but that can't be the case - the whole progress tracking thing is working fine on a local level. If I watch a stream, when it finishes, the show is marked with the watched icon when the page refreshes ("searching for episodes..."). If I watch part of a show and then stop the player, it shows as partially watched. If I select the same show again, it offers to resume from where I left off. 

The player DEFINITELY IS outputting the progress info, locally at least. The only thing that isn't happening is syncing that info back to the BBC website, which you've already said you can do by using the four messages you know that get posted to the API.

You don't necessarily need to be able to read that status back the other way because the watchlist updates automatically on the BBC server once an episode is marked as watched. 
Obviously, it would be nice if the addon could sync both ways so that shows watched outside of the plugin also show as watched but that's not essential to getting the main problem fixed.

**Comment by CaptainTK** [comment]
Apologies for not replying to this in due time, @kevwag .

You are right, the Kodi player is interacting with Skins to display the watched status of shows. As long as you don't restart Kodi, the skin "knows" that you already plyayed part of that stream/file. This mechanism relies on the fact that it is the _same_ stream. In case of iPlayer that is not necessarily the case. If you continue the same programme the next day, it will likely be a different stream (URL). It could either be a totally different CDN or at least a new set of cookies for authentication. The iPlayer stream URLs change frequently. Thus, Kodi cannot keep track of what it has already played. This would indeed need to be synced on the programme/episode level, not on the stream (URL) level.

_If_ it were possible to retrieve the watched information from Kodi by the add-on, it _could_ by synced back to the website.

However, as far as I know, there is no such mechanism. The add-on design in Kodi is a one way street. Add-ons "send" information to Kodi, which then creates a list of programmes/streams/files that you can play. Add-ons cannot receive information from the player. Once you hit play, the add-on is invoked once, and hands that particular file/stream URL to the player in Kodi. Whatever happens after that happens outside of the add-on.

The whole add-on design in Kodi is just a set of Python scripts that "create" something. There are no threads running continuously in the background, and there is especially no callback mechanism that would allow the Player to update the watched status. In short: I simply would not know _when_ to check for an updated status.

**Comment by Dis90** [comment]
Yes you can communicate with player. You need to create own player instance. Example how I did it in discovery+ add-on can be found here https://github.com/Dis90/plugin.video.discoveryplus/blob/6bebd96c4fee490deace3fdfafbaa169f4036f00/resources/lib/kodihelper.py#L409

To use resume time from service you need to set resume and total time to listitem. Example https://github.com/Dis90/plugin.video.discoveryplus/blob/6bebd96c4fee490deace3fdfafbaa169f4036f00/resources/lib/kodihelper.py#L203

**Comment by CaptainTK** [comment]
Thanks for sharing, @Dis90 !

That’s a really complicated solution. To save me some further research: What is the reason you did not submit D+ to the official add-ob repo? The usage of Widevine? The wrapped player?

To be honest: I don’t like the idea of wrapping the player like that as it means additional adaptations every time something changes on the Kodi side of things.

**Comment by Dis90** [comment]
Yep it is complicated and things can break on Kodi updates but it's only way I have found to achieve this feature. I don't think that type of updates happens often. Currently I can't remember any and I have used this method for at least 2 or 3 years. For some reason Up Next integration sometimes breaks on Kodi updates and I have to change some things in this player stuff.

Reason for why Discovery+ is not submitted to official repo is just my laziness :D And because in past login didn't work and users have to manually extract cookies from browser (not so user friendly). Now login works with device linking (add-on gives pin code which user put to discovery+ website).

So I don't anymore see any other obstacles why it can't be submitted to official repo, just my time is very limited.

**Comment by kevwag** [comment]
@CaptainTK  I gotta say, for someone with so little time, Dis90 is probably one of the most responsive  devs in the entire Kodi community. Whenever I've reported a bug (and I've reported a few!) he's fixed them within a few hours. He's also added a few new features that myself and other users have asked for. I think quite a few addons use this wrapped player solution - if you install IMDB Helper from the Kodi repo, it has an option in the settings to select the player to use and there are a number of other addons listed. Why would that or the use of Widevine be a reason not to submit to the official repo? Inputstream Helper uses Widevine, as does Catchup-TV-and-More - both included in the official repo.


@Dis90 you absolutely should submit it to the Kodi repo, it's full of addons for niche services and stuff hardly anyone would want but there's a dire need for addons providing the mainstream services.
I wouldn't worry about updates breaking it. There's stuff in the Kodi repo that hasn't worked for years and you're much more responsive than that! (Before you do submit though, there's a minor glitch when marking stuff watched or unwatched on Kodi Nexus. The busy spinner just stays spinning and you have to exit the addon. The item does get marked watched / unwatched so it seems to be hanging-up when the list refreshes).
