### ISSUE TITLE
Plugin isn't setting the "episode" mediatype via setInfo() for the listitems.

### ISSUE THREAD

**Issue by berkhornet** [vonH/plugin.video.iplayerwww#350]
Hi. I reported an issue against my current skin (Arctic Horizon 2) at https://github.com/jurialmunkey/skin.arctic.horizon.2/issues/403. The skin author has coded a workaround but asked me to advise you that iPlayer WWW isn't setting the "episode" mediatype via setInfo() for listitems. For example watched episodes were not being shown as watched when using the skin.

The skin author advised that whilst the overall cost of checking Container.Content() is relatively small, it is still a waste of CPU resources for a skin to need to add these types of workaround for plugins not properly setting the listitem mediatype.

Many thanks.

**Comment by CaptainTK** [comment]
Thanks for reporting this. I had no idea 
 that these settings actually make a difference. So far, I tried to set as few properties as possible.

I‘ll include this in the next update, but that may take 2-3 weeks as I am out if town.

**Comment by berkhornet** [comment]
Thanks for your response. Happy to test if you need any help.

Mick
________________________________

**Comment by CaptainTK** [comment]
@berkhornet: Please check if https://github.com/vonH/plugin.video.iplayerwww/commit/1d824f92d3ddcf8992c8ef7ae1c775e1c0eeca39 fixes the issue for you. I am not sure this is the right way to do as it sets the mediatype to "episode" for everything, even directories and radio/audio content.

However, I can hardly find any documentation on the mediatype setting, and what effects it has.

**Comment by berkhornet** [comment]
Many thanks for the update.

It has resulted in some detrimental changes to some lists displayed in the skin I am using (Arctic Horizon 2).I will do some more investigation and get back to you.

Regards

**Comment by berkhornet** [comment]
Hi. I have completed some further testing. This has been complicated by the fact that the since I raised the issue, a workaround has been added to the skin that overcomes the issue. As far as I can tell all is ok.

**Comment by CaptainTK** [comment]
Well, from what I understand, that fix will be reverted by @jurialmunkey, so we do need to fix it on this end.

You mentioned before this resulted in some detrimental effects. Could you elaborate on that, please?

**Comment by berkhornet** [comment]
Good Morning

Please ignore my comment re. detrimental effects - some of my Kodi settings had got screwed up!

The original problem I reported to the skin author was that "watched flags" for episodes from some video add-ons were not being displayed. This is all now working without your latest commit thanks to an update to the skin.

Having thought about this further, I'm told it is best practice to set the mediatype, not sure it makes sense to set the mediatype to "episode" if there is no season/episode number information available.

The skin I'm using can handle both situations (mediatype not set to episode; mediatype set to episode but with no episode number available.

So I am happy if the commit is released or not. Perhaps wait and see if other users report similar problems.

Thanks again for your help.

**Comment by CaptainTK** [comment]
Fixed by 11b0fd964ad056be057bc559e9a6d3b803570114.
