### ISSUE TITLE
TMDBHelper player?

### ISSUE THREAD

**Issue by t0mtee** [vonH/plugin.video.iplayerwww#351]
This would be great as it would allow you to play items straight from the library and there shouldn't need to be any changes to the actual plugin. I've tried making it myself, but I'm not knowledgeable enough in Kodi plugins to know how to make one.

**Comment by CaptainTK** [comment]
From what I can tell, the instructions to achieve this are listed [here](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function). It seems fairly easy, but it would not be part of this add-on. Basically, you need to create one file to be shipped with TMDBHelper that will tell TMDBHelper how to use the search function of this add-on. You should request it as a feature at TMDBHelper.

**Comment by t0mtee** [comment]
Ok, will do

**Comment by t0mtee** [comment]
Hey @CaptainTK, jurialmunkey, the author of TMDBHelper, is trying to make a player and has made pretty good progress however cannot quite make it work for all shows due to a lack of metadata in the addon. Could you take a look at what they need and see if you could make the changes? That would be greatly appreciated: [link](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/839)
