### ISSUE TITLE
Subtitle line breaks

### ISSUE THREAD

**Issue by sunjaxx** [vonH/plugin.video.iplayerwww#354]
Hello, me again!

I think line breaks (or lack of) are not being maintained in the conversion. This might be a side effect of the (span?) changes recently introduced to fix the colour issue. 

For example ("Happy valley", Season 2 , Episode 4), the two-line subtitle:

`<p begin="00:55:05.160" end="00:55:08.400" region="agr_2_20_38_4_after" style="S2" xml:id="C998_1"><span style="S3">Do you understand what I'm saying,</span><br/><span style="S3">then?</span><span style="S6"> I...</span><span style="S3"> Nothing is illegal.</span></p>`

![bbc](https://user-images.githubusercontent.com/30780852/216816148-797fb25d-a3bb-440e-982a-ece8f0cf84d0.jpg)

becomes a four-line subtitle:

```
1003
00:55:05,160 --> 00:55:08,400
<font color="#ffffff">Do you understand what I'm saying,</font>
<font color="#ffffff">then?</font>
<font color="#00ff00"> I...</font>
<font color="#ffffff"> Nothing is illegal.</font>
```

![kodi](https://user-images.githubusercontent.com/30780852/216816155-f4fd8473-0c3a-4b20-a9e5-d48e8018f753.jpg)

Thanks!

**Comment by CaptainTK** [comment]
Actually, that is just an old-style subtitle, which was always treated that way. No doubt about it, this is wrong.

This should fix it: fef1b806265b242118d7d66f6cbf3a763b74a15e.

**Comment by CaptainTK** [comment]
Although this might not fix it completely, as it will now be a single line. Subtitle formatting is really a pain...

**Comment by sunjaxx** [comment]
All line breaks are now indeed gone, even the ones that should be there, for example:
 
![Screenshot_20230205-174652](https://user-images.githubusercontent.com/30780852/216836231-08007a0a-59fb-4b06-9bc3-7cb6685d3c98.jpg)

Shouldn't the regex still look for `<br/>` and replace them with `'\n'` - or something like that?

Thanks!

**Comment by CaptainTK** [comment]
In case of this particular subtitle file the <br/> are in between the </span and the next <span… Thus, they are completely ignored by the script, which matches on the span pairs.

**Comment by sunjaxx** [comment]
FYI, the conversion done by the get_iplayer script (with mono=false, to keep the colors) seems to work well: is it an idea to re-use some of that?

https://github.com/get-iplayer/get_iplayer/blob/4d2e55a1eed45e89ed0e4e51e3bf4d738698c615/get_iplayer#L7658

**Comment by CaptainTK** [comment]
That is not helpful as it is Perl code, which just doesn't work the same as Python.

Nevertheless, I think I figured something out. Give this a try: 46536c388df3ba6bd9f23fccf50f829161eba085.

This should create correct subtitles for old and new format, although it will create useless (empty) `<font ...></font>` groups for old style subtitles. These are caused by the line breaks, which also get (useless) colour formatting.

**Comment by sunjaxx** [comment]
Thanks, no issues so far with this version!
