### ISSUE TITLE
IndexError in episode listing

### ISSUE THREAD

**Issue by ahgee2** [vonH/plugin.video.iplayerwww#357]
This exception was triggered by navigating to Categories -> Drama and Soaps -> The English, though the same thing seems to happen with other episode listings. 
[kodi.log](https://github.com/vonH/plugin.video.iplayerwww/files/11283443/kodi.log)
Please let me know if I can help debug - and thanks for all your efforts with this add-on.

**Comment by guy99au** [comment]
Same here. Program directories will not open, cannot access episodes.

**Comment by CaptainTK** [comment]
4.0.14 fixes this issue and is on its way, see https://github.com/xbmc/repo-plugins/pull/4307.

**Comment by ahgee2** [comment]
Thanks - tested on my Kodi box and all working fine now.
