### ISSUE TITLE
Categories/Documentaries failing

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#36]
Here is a fix.
https://github.com/primaeval/plugin.video.iplayerwww/commit/0ee70454e78556d6592febcca95378c2de5f864b

**Comment by CaptainTK** [comment]
My bad, this his was introduced with 09a9fd622f0e17303fd163ca8ca732c79f80e36a and I didn't manage to properly test it.

**Comment by ihurst** [comment]
Think you'll find it was my mistake CaptainTK so don't think you should be apologising :) 

Sorry - I've also done a quick check that I didn't cause issue anywhere else.
