### ISSUE TITLE
Live Streaming from Wimbledon.

### ISSUE THREAD

**Issue by praspp** [vonH/plugin.video.iplayerwww#360]
Live streams from Wimbledon are down.
I attach the log.
Playback of TV channels and VOD content works fine.
@CaptainTK -  Can you take a look at this?

K19.5, FIre TV Cube 2, Fire OS 7,  iPlayer WWW 4.0.14

[iPlayer_kodi_log.txt](https://github.com/vonH/plugin.video.iplayerwww/files/11957910/iPlayer_kodi_log.txt)

**Comment by CaptainTK** [comment]
The error messages originate in Inputstream Adaptive. Therefore, this does not appear to be related to this add-on.

Please check if you are using the latest version of Inputstream Adaptive, and raise an issue with its maintainers if necessary.

**Comment by praspp** [comment]
@CaptainTK 
Yes, I am using the latest version of ISA on K19.5. The same problem with Wimbledon live streams also occurs on K20.1. Playback of TV channels and VOD library (also from Wimbledon) works. Can you check if you have this problem?

**Comment by CaptainTK** [comment]
I cannot check because I am out of town. I believe you that this issue occurs, and I am confident it would occur on my setup as well.
However, the error log clearly shows that the issue is in ISA. Raise an issue with the ISA team, please. They need to look into this, I cannot.
