### ISSUE TITLE
Live mediaselector now requires authentication token

### ISSUE THREAD

**Issue by richEQ** [vonH/plugin.video.iplayerwww#362]
Hi there.
It appears the BBC has changed, or at least set up new URLs for the radio streams.
this project has the details:
https://gist.github.com/bpsib/67089b959e4fa898af69fea59ad74bc3

dead:
http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/http-icy-mp3-a/vpid/bbc_6music/format/pls.pls

not dead:
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_6music/bbc_6music.isml/bbc_6music-audio%3d96000.norewind.m3u8

I can confirm the old ones no longer work from the comand line and the new ones  do from the comand line ( using mpv )

I've spent a little while digging around the python code for the addon, but I'm afraid my python is NOT strong.. and debuging any changes is I think beyond me..
Can anyone help?

**Comment by CaptainTK** [comment]
Thanks for the notification. I will take a look at it.

**Comment by CaptainTK** [comment]
The real issue here (at least for 4.x of the add-on) is that the Beeb now require an authentication token to access the mediaselector URL. If that is passed correctly, the rest of the add-on should work as expected again.

The suggested hard links to streams is not a proper solution, as it will break again if these streams change location.

**Comment by dimkroon** [comment]
I  made this comment on the Kodi Forum, but only just now noticed this discussion here:

e.g. to listen to radio one, you need to make an authenticated request to the radio one page on BBC sounds. Authentication is just like iplayer, the same cookies.
The page contains data that can be obtained very similar to ipww_video.ScrapeJson(), but with a slightly different regex.
This data has a field that indicates whether the user is signed in, so authentication can be handled in the same way video now does.
And data also contains the JWT token needed in the query string to request radio one's media selector.

A test where I managed to get a valid media selector can be found at [https://github.com/dimkroon/iplayer_test...55C8-L55C8](https://github.com/dimkroon/iplayer_tests/blob/583982e546f21d42cd07f4c9e9645b7c8821ecef/web/test_iplayer_radio_api.py#L55C8-L55C8)
From there on it's just business as usual, I guess.

**Comment by CaptainTK** [comment]
Thanks a lot @dimkroon! Sounds too good to be true, but I will investigate further. If it is that simple, we should be fine.

I tried to understand what they are doing in a browser (debug mode), but the jwt token returned as a JSON object was different from the one used in the end. I couldn’t figure out what happened in between.

**Comment by CaptainTK** [comment]
You were right, piece of cake. Thanks again, @dimkroon .
