### ISSUE TITLE
Aired date no longer working?

### ISSUE THREAD

**Issue by CaptainTK** [vonH/plugin.video.iplayerwww#37]
Users report that the aired date no longer works, see http://forum.kodi.tv/showthread.php?tid=239378&pid=2155096#pid2155096.
@ihurst, please verify these reports. If inaccurate, feel free to close this issue.

**Comment by ihurst** [comment]
Found a few examples in channel highlights such as the following episodes:
 "Doctor Who - Series 9: 7. The Zygon Invasion"
 "The Kennedy: 5. Camping"

Interestingly these are displayed if we go via A-Z.

Still working on why Aired Date not captured for some episodes in some places :(

**Comment by CaptainTK** [comment]
Thanks for looking into this. If it only affects some episodes, it is not that urgent. I was first under the impression that everything was affected. However, being cut off from my Kodi installation I was unable to test for myself.

The more critical issue was #36 anyways, which is why I released 1.2.7 in the meantime.

**Comment by ihurst** [comment]
Looking at this I don't think it is an issue. The Problem is that some of the episodes in grouped content only appears once without the First Shown date (aired date). I'll leave open for now to see if we get any update from the reporter.

**Comment by CaptainTK** [comment]
Agreed. If this was what the reporter referred to, then this data simply isn't there one the Highlights page.

Thanks for your work, anyways and my apologies for opening the issue.

**Comment by CaptainTK** [comment]
There was at least one more bug which rendered the aired date empty, it was in ParseAired, which tried to parse only the first character of the aired date. This was fixed in adc3240eeb23a17f638c77c35b51ede44916257b.

However, after this fix, the aired date of every episode shows up as 30/11/65535 for me. @ihurst can you please check what's wrong with the date?

**Comment by primaeval** [comment]
My master version has correct aired dates everywhere. :)

**Comment by CaptainTK** [comment]
Fixed by adc3240eeb23a17f638c77c35b51ede44916257b.
