### ISSUE TITLE
Subtitles don't work on Welsh language content

### ISSUE THREAD

**Issue by dashavoo** [vonH/plugin.video.iplayerwww#373]
Using 4.0.17

Subtitles don't seem to work on Welsh language content despite being available when viewing on the website. One example is [episode 1 of Pren ar y Bryn](https://www.bbc.co.uk/iplayer/episode/p0gqsyzw/pren-ar-y-bryn-pennod-1) but I've tested on a few  programmes with the same result.

The subtitles that I can get on iPlayer are in English, so don't match the audio language. I don't know if that is related.

**Comment by CaptainTK** [comment]
This programme has two different IDs. One is type "original", the other is "technical-replacement". "original" does not have subtitles, "technical-replacement" does.

Currently, the add-on does not distinguish between different IDs, it randomly uses whatever occurs first in the JSON.

Options to fix this:
1. Select ID based on priority (Is "technical-replacement" always preferred over "original? What other types should be ordered how?)
2. Call mediaselector for all IDs (What are the criteria to choose stream and subs afterwards?)

On a side note, @dashavoo : I don't believe this is related to Welsh language content, it is pure coincidence that this happens for these programmes.

**Comment by dashavoo** [comment]
There is a 3rd option:

It seems that get_iplayer prefers to use original before technical, but if subtitles have been requested it will [prefer](https://github.com/get-iplayer/get_iplayer/blob/c58424a0e000f9a1b4d5d3cae30fdc85cc30384e/get_iplayer#L3662) the first version that has them.

> I don't believe this is related to Welsh language content, it is pure coincidence that this happens for these programmes.

Aah, that makes sense. When subtitles don't work on English programmes I just assume they aren't available and watch it without. I only checked because I knew S4C Clic has subtitles in both English and Welsh (but no up to date Kodi addon).

Thanks for looking into this so quickly, BTW! This is one of my most used Kodi addons and I've never had any major issues.

**Comment by CaptainTK** [comment]
That will be rather difficult to implement as the add-on is currently not designed to handle fallbacks. It just goes for one specific stream. Using fallbacks would require to change that whole concept.

**Comment by CaptainTK** [comment]
It turns out you were lucky these streams played at all. After adding prioritization to prefer technical_replacement over original, the streams failed to play entirely due to a bug in download_subtitles.

**Comment by dashavoo** [comment]
> After adding prioritization to prefer technical_replacement over original, the streams failed to play entirely due to a bug in download_subtitles.

Ah, that explains it! I tried changing the prioritisation myself and found myself unable to watch at all.

Thank you so much for the quick work! Looking forward to trying it out.
