### ISSUE TITLE
Subtitles: when two people speaking, only one shown.

### ISSUE THREAD

**Issue by dashavoo** [vonH/plugin.video.iplayerwww#377]
I'm using a2eb511092207b3b97da6a23896c6b99110bfea7 after you fixed #373 .
I've noticed a fair amount of subtitles which don't show, and after finally doing a side-by-side with iplayer in the browser I have realised it happens when iplayer shows two sets of subtitles simultaneously.

An example is:
```
346
00:41:55,190 --> 00:41:57,190
<font color="#ffffff">.
      </font><font color="#FFFFFF"> Why did you tell Ruth?</font><font color="#ffffff">.

.
         </font><font color="#408080"> I had no choice!</font><font color="#ffffff">.
</font>
```
which comes from `.kodi/userdata/addon_data/plugin.video.iplayerwww/iplayer.srt` when watching [this video](https://www.bbc.co.uk/iplayer/episode/p0gtlrtm/pren-ar-y-bryn-pennod-4?seriesId=unsliced).

In the browser it looks like this:
![image](https://github.com/vonH/plugin.video.iplayerwww/assets/3750013/7a01aaf8-1f56-4489-8a03-bb1322b56785)

and in Kodi it looks like this (only shows the first of the two speakers):
![image](https://github.com/vonH/plugin.video.iplayerwww/assets/3750013/221fc26f-7b9e-4ef8-8535-9fce8e0cc748)

**Comment by CaptainTK** [comment]
I am pretty sure this worked before. I distinctly remember working on multiline subs like this.

Which version of Kodi are you using, so I can test with a similar setup?

**Comment by dashavoo** [comment]
Nexus 20.3 (LibreElec 11).

**Comment by CaptainTK** [comment]
Thanks. I can't really test right now, but my best guess is that Kodi has troubles parsing empty lines within a subtitle.

8824ef85b5406d2f6f9d1ae773d01144b4c55181 should work around that. I would highly appreciate if you could give this a try and report back if it helps and if there are any side effects.

**Comment by CaptainTK** [comment]
Looks good to me. Please report back if you still see these in 4.1.0 (upcoming release).
