### ISSUE TITLE
Live TV feeds are 2 hours behind

### ISSUE THREAD

**Issue by gmjh123** [vonH/plugin.video.iplayerwww#378]
On fire 4k max using version 4.1 of your add-on, the live feeds show the correct program in the live listings, but the feed is 2 hours behind. And it's not possible to forward it to live. Can this be fixed? Thanks very much.

**Comment by CaptainTK** [comment]
That‘s odd. Unless you right click and select “Play from Start“ the code in 4.1.0 should do exactly the same as before and not pass any offset to the player.

Can you verify three things, please?

1. Compare the live stream to the one on the website. Is that where you see the 2 hours difference or just between the listing and the stream? The latter may indicate an issue with the listings.
2. Downgrade to 4.0.x to check if you get a different stream?
3. Which version of Inpustream Adaptive are you using? This may be a bug in the add-on, or or it may be a bug in IA.

Thanks a lot in advance.

**Comment by gmjh123** [comment]
I downgraded to an earlier 4.0 version and that made no difference. But
oddly when I went to upgrade it to the latest version of your add-on the
time issue went away. So I have no idea what was going on there.
Unfortunately I now have the same problem that's been reported here and on
Kodi where the live streams buffer after a few seconds and won't stop
buffering every few seconds.
https://forum.kodi.tv/showthread.php?tid=353349&pid=3169647#pid3169647
I'll try downgrading to Kodi 20 as suggested there and see if it helps.
I can play your addon without buffering or time issues on another preferred
device but that has another issue which I'll open in another post. Thanks
very much

**Comment by CaptainTK** [comment]
Now you lost me.

1. The buffering issue is not related to this add-on, but was caused by a bug in the beta version of  Inputstream Adaptive for Kodi 21. It will only affect you if you are using on Kodi 21 using Inputstream Adaptive 21.4.3 or lower. If that is the case, please update Inputstream Adaptive to 21.4.4 or later and the issue will go away.
2. Are you still experiencing the time lag or not? If not, let's close this here, please.

**Comment by gmjh123** [comment]
> Now you lost me.
> 
> 1. The buffering issue is not related to this add-on, but was caused by a bug in the beta version of  Inputstream Adaptive for Kodi 21. It will only affect you if you are using on Kodi 21 using Inputstream Adaptive 21.4.3 or lower. If that is the case, please update Inputstream Adaptive to 21.4.4 or later and the issue will go away.

I'm on Kodi 21 and inputstream adaptive 21.4.8. The issue of buffering has not gone away. I only get non-stop buffering on live channels however, catch up shows do not buffer. If this issue is reported as resolved however, I'm going to have to assume that the fault is somewhere on my end, slow VPN connection etc 

> 2. Are you still experiencing the time lag or not? If not, let's close this here, please.

I thought I'd already said that the time issue is now resolved. But yes I'll close this issue now.

**Comment by CaptainTK** [comment]
Thanks for the explanation and closing here. Actually, the buffering you explain is perfectly normal on slow connections. The bug in 21.4.3 meant that playback would stop and not recover.

Kindly note that usage of a VPN is not supported for this add-on. Whatever you do in that respect is at your own risk.
