### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by CaptainTK** [vonH/plugin.video.iplayerwww#38]
Search seems to take very long and may not terminate at all.

See http://forum.kodi.tv/showthread.php?tid=239378&pid=2156820#pid2156820, http://forum.kodi.tv/showthread.php?tid=239378&pid=2157440#pid2157440 and following posts.

**Comment by primaeval** [comment]
I've got a soup version that works. I'll see if I can make a branch with just that change for you. https://github.com/primaeval/plugin.video.iplayerwww/commit/4adea6972568e30facfefc8dd37b2e64ccb9b52a
I think the original search is getting stuck on a missing synopsis. 
Also I don't think multiple pages is necessary as it just takes a long time and finds a lot of unavailable programmes.

**Comment by primaeval** [comment]
Here is a version that can be pulled straight into yours without all the Highlights changes.
https://github.com/primaeval/plugin.video.iplayerwww/commit/16b140ea3c82511061c70a573cfd90311af3a172

**Comment by CaptainTK** [comment]
Thanks for the proposed changes and for looking into this. This seems like a pretty comprehensive fix, so I would like to test and understand it prior to merging. Please feel free to add this to the pull request for Highlights, I will then look at both at the same time as soon as I get to it.

**Comment by CaptainTK** [comment]
Regarding single vs. multi-page search. Please see my comments at http://forum.kodi.tv/showthread.php?tid=239378&pid=2157578#pid2157578. I am open to make a single page search an option. However, I firmly believe the multi-page search should be the default as the search results on the website are just too chaotic.

**Comment by primaeval** [comment]
I agree the search results are pretty insane. But in all my tests I didn't find anything useful after page 1. For example Eastenders gives 14 pages of non-available programmes. I think they are gearing up to link the search results to their store so they can sell you the unavailable programmes.

**Comment by primaeval** [comment]
This change was in my master branch already. I just pulled it into a seperate branch for a quick fix.

**Comment by CaptainTK** [comment]
Good point, I never thought about the Search as part of the plan to roll out their shop. You might be on to something there.

I did get results in my tests which made sense. Can't recall what I was searching for and it found some interviews/related stories after several pages of unavailable junk.

**Comment by primaeval** [comment]
Highlights, Groups, Categories and Search are looking pretty robust in my master branch right now, with some pretty progress bars and persistance. See if you can break it when you get some free time.
