### ISSUE TITLE
Collections have stopped working

### ISSUE THREAD

**Issue by robertoldaker** [vonH/plugin.video.iplayerwww#45]
Hi,

This plugin was working perfectly a few days ago but today it has stopped finding collections of programmes.
e.g. if you goto "Channel Highlights->BBC Four->Collection: The Bridge..." it just hangs and eventually returns an empty page. 

If you search for "The Bridge" you get a link to "The Bridge: 8 Episodes available" then if you click that link it again returns an empty page.

Seems to fail for other collections as well. 

Great plugin by the way with lots of useful features and as I say was working fine up until recently.

I am using 1.2.9 on Kodi 14.2

Rob.

**Comment by primaeval** [comment]
Try grabbing the zip from here instead of the Kodi repo until it gets pushed there.

**Comment by robertoldaker** [comment]
Great that worked. Seems all fine now.

Rob.
