### ISSUE TITLE
No video just audio

### ISSUE THREAD

**Issue by jwab76** [vonH/plugin.video.iplayerwww#46]
Hi updated my kido 3.5.1 and added latest iplayerwww from github via zip file. Can browse titles fine but when I play all I get is the audio, no video. Plays like an audio file from the music menu.

Running on orginal xbox. Is this a known issue?

Thanks

**Comment by primaeval** [comment]
I doubt if an original xbox has the power to play h264 video, especially the 50fps HD sources from iplayer.

**Comment by jwab76** [comment]
That depends on the resolution of the video. It plays 480p h264 just fine, and can even play 720p if the audio is mp3. The previous version of iplayer.lite offered stream selection. I found the 800kbps was perfect. How does this replacment choose what you see?

**Comment by primaeval** [comment]
This is the same. Go to Settings\Streams. Turn off Play Stream automatically. Find the best stream manually, then turn automatic back on.

**Comment by primaeval** [comment]
It finds the highest bitrate available, not what your machine can handle. I'm not sure if its possible to make it adapt to what your machine can handle automatically but I didn't write the addon.

**Comment by jwab76** [comment]
Brilliant mate. Never saw that settings menu. You gotta goto Plugin Settings from the main plugins menu. Can set it to choose a certain bitrate or just manual select like you said. Set it to 1Mbps as it gives good picture and speed. All good now. Many thanks
