### ISSUE TITLE
add radio content

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#62]
Someone requested radio content.
http://forum.kodi.tv/showthread.php?tid=239378&pid=2228930#pid2228930

**Comment by primaeval** [comment]
I've made a start on radio.
https://github.com/primaeval/plugin.video.iplayerwww/tree/radio

**Comment by primaeval** [comment]
Have you tested any of this on your Android box? I wonder if there are any Python 2.6 issues.

**Comment by CaptainTK** [comment]
That'll be the last thing I do. But I promise I'll do it. ;-)

If you've got any more fixes, please keep them coming. I plan to do the Android test tomorrow and release after that.

**Comment by primaeval** [comment]
It works ok on rpi.

**Comment by CaptainTK** [comment]
Fixed by b46b98317863e6773ccb57065b58c72b39afa30e
