### ISSUE TITLE
Highlights curtently does not terminate for BBC Three

### ISSUE THREAD

**Issue by CaptainTK** [vonH/plugin.video.iplayerwww#63]
At the moment Channel Highlights -> BBC Three does not terminate, most likely some regexp gets stuck.

**Comment by primaeval** [comment]
BBC Three is redirecting to some Daily Drop page in Kodi. It is different to the page you see in a browser. I can't see how to stop it so far.

**Comment by primaeval** [comment]
Fixed. They have moved the url.
