### ISSUE TITLE
feature request: add proxy support

### ISSUE THREAD

**Issue by chewitt** [vonH/plugin.video.iplayerwww#7]
I don't have a VPN service but do have a perfectly good private http proxy in the UK that worked fine until the recent changes. Using a proxy is (still) preferable to a VPN as a) I don't need to manually connect and disconnect VPN services before/after iPlayer use, or b) leave a tunnel active 24x7 which then interferes with other plugins that don't work when geo-locked to a UK address, c) spend; the proxy costs me £0.00.

I was able to re-add the previous level of support which retrieves the m3u8 file that contains URL's for all the segments and do some hackery to change http:// into http://user:pass@proxy:port:url, but this appears to result in a second m3u8 file that contains more non-proxied URL's, e.g. 

http://vod-hls-uk-live.edgesuite.net/usp/auth/vod/piff_abr_full_hd/932c94-b06hk6fl/vf_b06hk6fl_2bbc4def-47b8-48ac-aad6-0753a29fbe9a.ism.hlsv2.ism/vf_b06hk6fl_2bbc4def-47b8-48ac-aad6-0753a29fbe9a.ism.hlsv2-audio=128000-video=5070000.m3u8?__gda__=1444621498_95519e1c536fc7c2e4620c59e36f567a

At this point my python n00bness and incomplete understanding of how things work stops progress. I will go peek at get_iplayer for further hints, but I suck at perl too :)

http://sprunge.us/jYcb <= hackiness starts at L749, with the redirect to OpenStream at L777 - this uses the proxy settings bits from your earlier plugin added back to settings.xml.

Any pointers? - I'd be happy to provide access to a working proxy to get this feature added back.

**Comment by ihurst** [comment]
Christian,

Sounds like we are at similar stage of being Python n00bies :-)

I'll take a look at this code tonight and see if I can provide any input

I've been looking at settings and other parts to get bbc sign in and favourites working. 

Is your code in github or should I just copy and paste the code at url provided?

Example proxy would be useful, save me setting something up.

Ian

-------- Original message --------

**Comment by CaptainTK** [comment]
Please do not add proxies to the add-on.

Please contact me by PM in the forum if you would like to discuss further.

**Comment by CaptainTK** [comment]
Won't fix.

**Comment by chewitt** [comment]
PM sent

**Comment by vonH** [comment]
Adding proxy support makes this a difficult area for repository submission. If the BBC were to ask us "why does this unauthorized add-on have proxy support, when it's only meant for UK users" it would be hard to answer.
