### ISSUE TITLE
show aac bitrate in overlay

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#71]
I think its up to us to fill in the bitrate, bits/sample, sample rate and audio channels for audio streams.

**Comment by primaeval** [comment]
I think this is a Kodi bug now. Using some test streams from here http://download.wavetlan.com/SVV/Media/HTTP/http-aac.htm the .aac and .m4a ones show bitrate but the .mp4 ones don't. The BBC streams use .mp4a in a .m3u8. I think it treats them as video not audio.

**Comment by primaeval** [comment]
The final segments are .ts in the inner .m3u8 which is usually video.

**Comment by CaptainTK** [comment]
I think that's not the point.

"listitem" in AddMenuEntry specifies the information Kodi uses for displaying things like bitrate and channels. However, all of this currently sets video-type parameters. There needs to be a different treatment for modes 211-214 and 131-135. Perhaps it even makes sense to have two different AddMenuEntry functions.

**Comment by primaeval** [comment]
The bitrate is showing up for live radio today. :) Was it a Kodi bug?
