### ISSUE TITLE
feature request: Favourites and Watching

### ISSUE THREAD

**Issue by ihurst** [vonH/plugin.video.iplayerwww#8]
Ability to access iPlayer functionation for quick links to programmes marked as favourites and programmes currently in the middle of watching.

These features would require the user to have a BBCiD login

**Comment by ihurst** [comment]
I am currently having a go at this in a fork I've created. Got the majority of it up and running.

**Comment by primaeval** [comment]
Is this working for you on version 1.2.1?. I get a signin Successful then Failed. I have double checked my BBCID.

**Comment by CaptainTK** [comment]
Please try 1.2.2. This might have been a bug in the translation, which said successful although it really failed.

Sorry about that, the translations are a requirement to get onto the official repo.

**Comment by CaptainTK** [comment]
Do you expect more bug fixes or features added in the near future?

My question is related to this: If this is it for the next week or so I will make a new release and push it to the official repo.

**Comment by ihurst** [comment]
I'm going to have a look tonight at any issues that may be connected with this work.

I'm looking at a new search feature - saving prev search terms.  But don't hold a release for this.

**Comment by primaeval** [comment]
Watching is not working for me since yesterday even in Firefox/Chrome. How about you? 
I get "This information is not currently available. " in Firefox/Chrome.

**Comment by primaeval** [comment]
Its ok now but the missing plot bug has reappeared. 
Please add a space to the default:
-        plot = episode.get('synopses').get('large') or ''
+        plot = episode.get('synopses').get('large') or " "

**Comment by CaptainTK** [comment]
Thanks for reporting, did that in 55ee25b39a528bbc65751225410db25787c58416.

Apart from the spaces, you also changed from single quotes to double quotes. Can you please explain that change? Sorry if this is a dumb question, I am still learning Python and yes, I still prefer C.

**Comment by primaeval** [comment]
I was following an example that showed "" giving an empty string but by the time it gets used in turns into None. I hoped double quotes had better magic but it didn't. So either quotes with a space should work.

**Comment by ihurst** [comment]
Just found out in openelec that you can select any menu item or directory and press 'c' to open a context menu that allows you to "Add to favourites" (This adds an bookmark to openelec)

Going to close this now :)

**Comment by primaeval** [comment]
@CaptainTK. In most scripting languages I am used to single quotes produce literal values and double quotes interpret variables. I was expecting something similar in python but it looks like quotes is quotes, double or single.

**Comment by ihurst** [comment]
@primaeval look like you're working on an interesting task "live recording". How's it going?

**Comment by primaeval** [comment]
@ihurst I'll pm you in forum.kodi.tv.

**Comment by ihurst** [comment]
@primaeval It is me on forum.kodi.tv but it's not allowing me to compose messages at the moment? Any ideas why? I get the standard "You do not have permission to access this page" when I try and hit reply to your message. I can see my user profile etc...

**Comment by primaeval** [comment]
@ihurst I sent you my email address. Lets cut out the middle man.
