### ISSUE TITLE
zombie DialogProgressBG's

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#85]
If a user presses the back button on a long running scraping function, the next time it is run a zombie DialogProgressBG will appear along with the new one.  

I can't find a way to close the old DialogProgressBG so I've asked on the kodi dev forum.
http://forum.kodi.tv/showthread.php?tid=260266

**Comment by CaptainTK** [comment]
I guess this is basically a bug in Kodi and there is nothing we can do about it, @primaeval.

If you concur, let's close this as won't fix. It makes no sense to keep it open forever.

**Comment by primaeval** [comment]
Yes, close it.
