### ISSUE TITLE
international Radio sources

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#87]
Find the sources for non-geo-blocked Radio.

**Comment by primaeval** [comment]
Here is a good list: http://www.radiofeeds.co.uk/other.asp
uk and nonuk:
```
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/llnw/bbc_radio_one.m3u8
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_med/llnw/bbc_radio_one.m3u8
```

**Comment by primaeval** [comment]
I've added an International option for live streams. Just need to work out how to do the catchup streams.

**Comment by CaptainTK** [comment]
Is there really international catchuo content?

**Comment by primaeval** [comment]
Yes. I didn't think it worked either before now. Its coming through the HTML5 beta player via DASH in Firefox and Flash swf in Chrome for me. I'm using Google's DNS 8.8.8.8 to test from DK. The addresses start like this:
```
http://aod-dash-ww-live.bbcfmt.vo.llnwd.net
```

**Comment by primaeval** [comment]
Interesting link about dash: http://forums.slimdevices.com/showthread.php?53229-Announce-BBCiPlayer-Plugin-%28UK-only%29&p=835193&viewfull=1

**Comment by primaeval** [comment]
With pc = iptv-all I get geoblocked. This is what we have now.
```
http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/b070wdly
```
But without it I get an xml dash manifest.
I just need to work out how to get Kodi to play it.

**Comment by CaptainTK** [comment]
AFAIK, DASH is currently not supported by Kodi, so this won't work.

Plus, DASH is currently only on iPlayer Beta. The Beeb is still fiddeling around with it and I don't want to integrate it before it is stable on their end. Simple reason: I would like to avoid the additional forum support required for things like that.

**Comment by primaeval** [comment]
Ok. 
I read somewhere that you could pull out the simple streams from dash without full Kodi support. 
I'll have a look at the other ways people grab the streams, like get_iplayer.
I can't stop when someone sets a challenge to fix things.

**Comment by CaptainTK** [comment]
It wasn't my intention to stop you. ;-)

I just won't be able to be of much help in coding before mid April.
