### ISSUE TITLE
HD streams for live TV are no longer available

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#88]
Looks like the Beeb are getting stingy and have turned off the HD streams.
http://forum.kodi.tv/showthread.php?tid=239378&pid=2260178#pid2260178

**Comment by CaptainTK** [comment]
It seems the Beeb changed something and live TV is no longer available for devices which require HLS.

It should be checked if other means can be used to offer HD live TV in the add-on.

**Comment by primaeval** [comment]
I can't find any addon or webpage with HD live streams now except Teleboy from Switzerland which is geoblocked. It's quite bizarre that you have to get quality UK TV from Switzerland.

**Comment by primaeval** [comment]
The get_iplayer develop branch can play them in HD.

**Comment by CaptainTK** [comment]
Which quality setting are you using and which bitrate do you see for HD?

I would assume they are still using RTMP, which is in line with the comments on the forum regarding a blu-ray player.

**Comment by primaeval** [comment]
They are the HLS Video Factory streams.
```
audio_bitrate: 128
authstring:
bitrate:    5380
expires:
ext:        mp4
identifier:
kind:       video
live:       1
priority:   102
server:
size:
streamer:   hls
streamurl:  http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d5070000.m3u8?
swfurl:     http://emp.bbci.co.uk/emp/SMPf/1.15.1/StandardMediaPlayerChromelessFlash.swf
type:       (gip_hvf_simulcast_5380) hls h264 1280x720 5380kbps stream (CDN: ll_hls_live/102)
video_bitrate: 5252

stream:     hvfhd2
```

**Comment by CaptainTK** [comment]
So they are back/still there. That's weird!

**Comment by primaeval** [comment]
They have moved from hls to hvf for video factory. https://github.com/get-iplayer/get_iplayer/blob/develop/get_iplayer#L8021

**Comment by CaptainTK** [comment]
[This](https://github.com/get-iplayer/get_iplayer/commit/6f81133911381d4e22fedc6a6f16d9cc8be74d11) seems to be the commit which added hvf in the first place.

However, some comments in [this](https://github.com/get-iplayer/get_iplayer/commit/59e86ed19895354229988656cc638a150566acf4) commit indicate that HVF will only work with ffmpeg v2.5 and newer. This would break compatibility with Helix.

**Comment by primaeval** [comment]
It works ok with Kodi 14.2 on Win7 32bit with this hvf link in a strm file:
```
http://vs-hls-uk-live.bbcfmt.vo.llnwd.net/pool_4/live/bbc_one_hd/bbc_one_hd.isml/bbc_one_hd-pa4%3d128000-video%3d5070000.m3u8?
```

**Comment by CaptainTK** [comment]
Sounds good. But where do they come from? I can't see them hard-coded anywhere.

**Comment by primaeval** [comment]
```
http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/bbc_one_hd/transferformat/hls?cb=95684
```
magic numbers again ;)

**Comment by CaptainTK** [comment]
I hate magic numbers. Is that random again or some sort of response by the swf-url they are using?

**Comment by primaeval** [comment]
I think it is from here: https://github.com/get-iplayer/get_iplayer/blob/develop/get_iplayer#L7640

**Comment by primaeval** [comment]
Voila! :) https://github.com/primaeval/plugin.video.iplayerwww/commit/8ce64e8e4f42ba77a1dccd047a232b3a9de032d0
