### ISSUE TITLE
feature request: ethnic programmes

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#93]
Someone asked for ethnic programmes. http://forum.kodi.tv/showthread.php?tid=239378&pid=2265315#pid2265315

> Can addon be made for http://www.bbc.com/nepali these video are not geo-restricted, and there are some other same format pages available for other ethnic groups like http://www.bbc.com/hindi , http://www.bbc.com/urdu etc.

**Comment by CaptainTK** [comment]
This would require an entire additional scraper and it is not part of iPlayer.

If somebody wants to pick this up, it should be in a separate add-on.

**Comment by primaeval** [comment]
I was hoping there was a hidden iplayer page somewhere that came up from one of the ethnic bbc sites but no-one has come up with a solution. Its best to forget about it for now.
