### ISSUE TITLE
feature request: Red Button

### ISSUE THREAD

**Issue by primaeval** [vonH/plugin.video.iplayerwww#97]
OTinley has asked for the Red Button live streams.
http://forum.kodi.tv/showthread.php?tid=239378&pid=2276062#pid2276062

I've made a branch with the links he sent.
https://github.com/primaeval/plugin.video.iplayerwww/tree/redbutton
It needs a few language translation strings.

This should work until someone finds a link to the index page for the streams. He says they have had the same address for at least 7 months.

What do you think?

**Comment by CaptainTK** [comment]
Don't think hard coded streams should be included in the add-on. If somebody wants to use them, an STRM-file seems the more logical choice to me.

If we could find a generic way to include Red Button streams, I would be more than happy to do so. My plan was to wait for some bigger event with several strams at the same time and then give it a try.

**Comment by primaeval** [comment]
Can you do some testing when you get back. All I could see on the streams was some test cards and one clip that repeated every 15 seconds on channel 9. I don't know if its the way they are meant to be, Kodi, or my connnection.

Have you got a Smart TV that you can sniff the stream indexes from?

**Comment by primaeval** [comment]
The trouble with strm files is that the chance of most people finding the Red Button strm file is close to zero.

If these links do work, how about adding an optional setting to enable them? 
"Red Button (Experimental)" enable (default off)

**Comment by CaptainTK** [comment]
I am back. But I am also about to leave again, so no time to work on this, sorry.

I also don't have a Smart TV (yet) to dig around, maybe later this year.

As nice as it would be to support this, I strictly oppose adding hard coded streams no matter which expert mode may be required to use them.

**Comment by primaeval** [comment]
According to Irn|Bru the only time the link source appears is during events which is too precarious to scrape. http://forum.kodi.tv/showthread.php?tid=239378&pid=2279196#pid2279196

Does it go against the Kodi rules to add hard links or are you worried about any legal problems?

If its just stability, then everyone is used to things coming and going on Kodi. It is just a hobby project after all.

**Comment by CaptainTK** [comment]
It's two things that I'm worried about:
1. Possible legal issues and
2. Managing expectations of users. I see the potential for this to create a lot of follow-up efforts.

**Comment by primaeval** [comment]
A lot of users are quite excited about this already but its your call, of course.

**Comment by primaeval** [comment]
irn|bru came up with the f4m streams. :)
More details are here: https://github.com/get-iplayer/get_iplayer/issues/171
I've got a redbutton branch that works with ak and llnw f4m streams.

**Comment by primaeval** [comment]
Here is a little program that spits out strm files for all the decent streams for all the channels including red button, if you want to compare the stream quality options.
https://gist.github.com/primaeval/276a3965194a8ee167a6
